### PR TITLE
Theming

### PR DESCRIPTION
**Pull request by neochapay**
Add theming support. Now we have 28 parametrs size, colors and other 

    itemWidthLarge;        //320
    itemWidthMedium;       //240
    itemWidthSmall;        //120
    itemWidthExtraSmall;   //72

    itemHeightHuge;        //80
    itemHeightExtraLarge;  //75
    itemHeightLarge;       //63
    itemHeightMedium;      //50
    itemHeightSmall;       //40
    itemHeightExtraSmall;  //32

    itemSpacingHuge;        //40
    itemSpacingLarge;       //20
    itemSpacingMedium;      //15
    itemSpacingSmall;       //10
    itemSpacingExtraSmall;         //8

    fontSizeExtraLarge;     //30
    fontSizeLarge;          //24
    fontSizeMedium;         //20
    fontSizeSmall;          //18
    fontSizeTiny;           //16
    fontWeightLarge;        //63
    fontWeightMedium;       //25
    fontFamily;         

    accentColor;            //#0091e5
    fillColor;              //#474747
    fillDarkColor;          //#313131
    textColor;              //#ffffff
    backgroundColor;        //#000000
    backgroundAccentColor;  //#ffffff

This is almost all the parameters that we need IMHO. All parametrs can be changed in json theme file and all application can change theme. I do not think it's a good idea but i dont know how to use that functional correctly...

### CODE REVIEW

**Comment by chriadam** [comment]
Potentially might be a good idea to add animation durations (opacity fade duration, menu expansion duration, etc) to the Theme, to avoid hardcoding stuff everywhere.  One other thing I see often is opacity values (e.g. for disabled options, etc) so it might be worth standardising theme values for that sort of thing too.

**Comment by neochapay** [comment]
I think commit ready

**Comment by eekkelund** [comment]
No other page works in "Glacier UI" example application than the main.qml. All other pages give the basic `[W] unknown:334 - file:///usr/lib/qt5/qml/QtQuick/Controls/Nemo/Header.qml:334:23: Unable to assign [undefined] to QQmlListProperty<QQuickItem>` Error. This is after two last commits, earlier almost all pages worked, except selectRoller and listView pages.

Also IMO font sizes are quite small(Maybe also itemHeights).

**Comment by neochapay** [comment]
@eekkelund Qt 5.6 ?

**Comment by eekkelund** [comment]
@neochapay Yes

**Comment by neochapay** [comment]
Use this example/touch/main.qml file https://gist.github.com/neochapay/81d4938c1a0f552a7b05dfe8533ff8e4 and send me log when you try run selectRoller and listView pages.

**Comment by eekkelund** [comment]
All the other pages started to work except listView, here is the output:
```
[D] onClicked:226 - Error:  qrc:/content/ListViewPage.qml:-1 File not found

[W] unknown:334 - file:///usr/lib/qt5/qml/QtQuick/Controls/Nemo/Header.qml:334:23: Unable to assign [undefined] to QQmlListProperty<QQuickItem>

```

**Comment by neochapay** [comment]
@eekkelund try clean build or remove examples/touch/qrc_*

**Comment by locusf** [comment]
@eekkelund @neochapay are you guys ready to merge this?

**Comment by neochapay** [comment]
@locusf i have some errors with examples and i can`t check...but if @eekkelund says all is ok - i think we can merge that

**Comment by eekkelund** [comment]
Well the example application doesn't work ATM at all, only the first page is visible. If you are able to fix this, @neochapay, then merge is ok for me. If you don't have time I could try to check what is causing the problem.

**Comment by neochapay** [comment]
Ready

**Comment by locusf** [comment]
Please fix paths like this: https://github.com/neochapay/qtquickcontrols-nemo/blob/d744fc4fb5e2fb522f85ef3cdd37b1dc09a8f3d9/examples/touch/main.qml#L130

**Comment by neochapay** [comment]
@locusf path of ?

**Comment by locusf** [comment]
All tests pass now for me. Listview isn't visible due to changes in sailfish qt, nothing to do with @neochapay code.

**Pull request merged**
